# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' intersectToList
#'
#' This function intersects a list of string vectors with a single string vector.
#' adpated from: https://jokergoo.github.io/2023/04/05/speed-up-over-representation-enrichment-analysis/
#' originally created by: Zuguang Gu
#'
#' @param lt A list of vectors of strings
#' @param x A vector of strings
#' @export
intersectToList <- function(lt, x) {
    .Call('_MultiPath_intersectToList', PACKAGE = 'MultiPath', lt, x)
}

